services:
  spark-master:
    image: jokeswar/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./data:/spark_data
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker-1:
    image: jokeswar/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./data:/spark_data
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
